name: dartros_msgutils
description: A Dart implementation of a ROS 1 Client Library
version: 0.1.0
repository: https://github.com/TimWhiting/dartros

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  actionlib_msgs: '>=0.1.0-0 < 0.2.0'
  std_msgs: '>=0.1.0-0 < 0.2.0'
  buffer: ^1.1.0
  dartx: ^0.7.0
 